### ISSUE TITLE
Move querying scheduled rewards to individual modules

### ISSUE THREAD

**Issue by bajtos** [filecoin-station/core#275]
See the discussion in https://github.com/filecoin-station/core/pull/259:

> It's the module's decision whether to use Meridian. `ethers` might even run in Zinnia, since for this we don't need to sign messages - or we could just use the `jsonrpc` endpoint directly - then we only need `fetch`. I think for this we need a way for Zinnia modules to log metrics.

```[tasklist]
### Tasks
- [ ] https://github.com/filecoin-station/zinnia/issues/421
- [ ] Release new Zinnia version and bring it to Station Core
- [ ] Update SPARK to use this new API
- [ ] Release new SPARK version and bring it to Station Core
- [ ] Rework Station Core to use this new metric provided by `zinniad`
```

**Comment by bajtos** [comment]
@juliangruber is this something we should consider for the DARC workstream or are you ok to duplicate the current code in Station Core to query scheduled rewards for another module?

**Comment by juliangruber** [comment]
Good question, let's decide as we work on the implementation
